baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tile Based Worlds'
buildFuture = true

[outputs]
  home = ["HTML", "JSON"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName  = "search-index"
  isPlainText = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = 'Techniques and processes to build tile based games or effects'
  show_reading_time = true
  recent_posts_number = 5
